apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-website
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: webnginx
    server: https://kubernetes.default.svc 
  project: default
  source:
    repoURL: https://github.com/deftdev-mimo/private-deploy.git
    targetRevision: main
    path: nginx/
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true